name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Documents/seygo/front-end/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Documents/seygo/front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Documents/seygo/front-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Run unit tests
        run: flutter test --no-pub
